In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("train.csv")

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.shape

(1460, 81)

In [5]:
 n_rows, n_cols = df.shape

In [6]:
n_rows

1460

In [7]:
n_cols

81

In [8]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [9]:
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [10]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [11]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [13]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [14]:
df.dtypes.GarageArea

dtype('int64')

In [15]:
df.dtypes.MoSold

dtype('int64')

In [17]:
df["MSSubClass"]

0       60
1       20
2       60
3       70
4       60
        ..
1455    60
1456    20
1457    70
1458    20
1459    20
Name: MSSubClass, Length: 1460, dtype: int64

In [18]:
df.MSSubClass

0       60
1       20
2       60
3       70
4       60
        ..
1455    60
1456    20
1457    70
1458    20
1459    20
Name: MSSubClass, Length: 1460, dtype: int64

In [19]:
type(df["MSSubClass"])

pandas.core.series.Series

In [20]:
df["PoolQC"].tail(10)

1450    NaN
1451    NaN
1452    NaN
1453    NaN
1454    NaN
1455    NaN
1456    NaN
1457    NaN
1458    NaN
1459    NaN
Name: PoolQC, dtype: object

In [23]:
column_list = ["PoolQC"]
df[column_list]

     PoolQC
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
...     ...
1455    NaN
1456    NaN
1457    NaN
1458    NaN
1459    NaN

[1460 rows x 1 columns]

In [24]:
df["PoolQC"]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1455    NaN
1456    NaN
1457    NaN
1458    NaN
1459    NaN
Name: PoolQC, Length: 1460, dtype: object

In [25]:
df[["PoolQC"]]

     PoolQC
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
...     ...
1455    NaN
1456    NaN
1457    NaN
1458    NaN
1459    NaN

[1460 rows x 1 columns]

In [27]:
col = df["PoolQC"]
col

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1455    NaN
1456    NaN
1457    NaN
1458    NaN
1459    NaN
Name: PoolQC, Length: 1460, dtype: object

In [28]:
type(col)

pandas.core.series.Series

In [29]:
col.name

'PoolQC'

In [30]:
col.dtype

dtype('O')

In [31]:
col.index

RangeIndex(start=0, stop=1460, step=1)

In [32]:
df["LotArea"].tolist()

[8450,
 9600,
 11250,
 9550,
 14260,
 14115,
 10084,
 10382,
 6120,
 7420,
 11200,
 11924,
 12968,
 10652,
 10920,
 6120,
 11241,
 10791,
 13695,
 7560,
 14215,
 7449,
 9742,
 4224,
 8246,
 14230,
 7200,
 11478,
 16321,
 6324,
 8500,
 8544,
 11049,
 10552,
 7313,
 13418,
 10859,
 8532,
 7922,
 6040,
 8658,
 16905,
 9180,
 9200,
 7945,
 7658,
 12822,
 11096,
 4456,
 7742,
 13869,
 6240,
 8472,
 50271,
 7134,
 10175,
 2645,
 11645,
 13682,
 7200,
 13072,
 7200,
 6442,
 10300,
 9375,
 9591,
 19900,
 10665,
 4608,
 15593,
 13651,
 7599,
 10141,
 10200,
 5790,
 1596,
 8475,
 8635,
 10778,
 10440,
 13000,
 4500,
 10206,
 8892,
 8530,
 16059,
 11911,
 3951,
 8470,
 8070,
 7200,
 8500,
 13360,
 7200,
 9337,
 9765,
 10264,
 10921,
 10625,
 9320,
 10603,
 9206,
 7018,
 10402,
 7758,
 9375,
 10800,
 6000,
 8500,
 11751,
 9525,
 7750,
 9965,
 21000,
 7259,
 3230,
 11616,
 8536,
 12376,
 8461,
 21453,
 6060,
 9464,
 7892,
 17043,
 6780,
 4928,
 4388,
 7590,
 8973,
 14200,
 12224,
 7388,
 6853,
 10335,
 10400,
 10355,
 11070,
 9066,
 15426,
 10500,
 11645,
 8520,
 10335,
 9100,
 2522,
 6120,
 9505,
 7500,
 6240,
 10356,
 13891,
 14803,
 13500,
 11340,
 9600,
 7200,
 12003,
 12552,
 19378,
 11120,
 13688,
 12182,
 5500,
 5400,
 10106,
 10708,
 10562,
 8244,
 16669,
 12358,
 31770,
 5306,
 10197,
 12416,
 12615,
 10029,
 13650,
 17423,
 8520,
 2117,
 7588,
 9060,
 11426,
 7438,
 22950,
 9947,
 10410,
 7018,
 4923,
 10570,
 7472,
 9017,
 2522,
 7180,
 2280,
 9416,
 25419,
 5520,
 9591,
 8546,
 10125,
 7000,
 4438,
 3500,
 11851,
 13673,
 12493,
 14364,
 8250,
 5604,
 10420,
 8640,
 13568,
 10900,
 10011,
 8450,
 9906,
 15660,
 3010,
 8990,
 8068,
 11475,
 10500,
 13472,
 1680,
 9950,
 1869,
 8521,
 3182,
 8760,
 15138,
 1680,
 10650,
 7851,
 1680,
 8773,
 9453,
 12030,
 8741,
 9000,
 3880,
 5000,
 10762,
 8880,
 10400,
 9142,
 11310,
 11317,
 159000,
 5350,
 4750,
 8366,
 9350,
 8400,
 8738,
 8791,
 8814,
 12435,
 12702,
 19296,
 9588,
 8471,
 5500,
 5232,
 12090,
 11207,
 8400,
 6900,
 7917,
 10728,
 39104,
 11764,
 9600,
 8314,
 7264,
 9196,
 19138,
 14450,
 10005,
 11287,
 7200,
 5063,
 9612,
 8012,
 4251,
 9786,
 8125,
 9819,
 8730,
 15611,
 5687,
 11409,
 16659,
 9600,
 7937,
 13710,
 7399,
 11700,
 14000,
 15750,
 16226,
 13704,
 9800,
 18386,
 10386,
 13474,
 7920,
 12342,
 12378,
 7685,
 8000,
 7800,
 215245,
 9600,
 7795,
 13005,
 9000,
 9900,
 14115,
 16259,
 12099,
 10380,
 5820,
 11275,
 5000,
 10846,
 11600,
 11888,
 6402,
 10624,
 8176,
 10655,
 8198,
 9042,
 164660,
 14157,
 9135,
 14145,
 12400,
 14191,
 8400,
 8544,
 8849,
 2592,
 6435,
 12772,
 17600,
 2448,
 20431,
 7820,
 5271,
 9084,
 8520,
 8400,
 11249,
 9248,
 4224,
 6930,
 12011,
 7540,
 9144,
 7301,
 1680,
 18800,
 10690,
 9500,
 9150,
 7800,
 9830,
 8121,
 17120,
 7175,
 10634,
 8200,
 10020,
 8846,
 11143,
 11394,
 8123,
 5000,
 7200,
 9245,
 9000,
 53107,
 3182,
 8410,
 7200,
 9382,
 12474,
 8405,
 12209,
 8339,
 7446,
 10134,
 9571,
 7200,
 7590,
 8967,
 8125,
 14963,
 8767,
 10200,
 12090,
 10364,
 9991,
 10480,
 15576,
 14154,
 10800,
 9571,
 34650,
 4403,
 8960,
 11228,
 8899,
 7844,
 22420,
 8160,
 8450,
 7060,
 16635,
 21750,
 9200,
 9000,
 3378,
 12800,
 8593,
 6762,
 11457,
 1680,
 5586,
 1920,
 10839,
 1890,
 10667,
 4400,
 6000,
 4280,
 12354,
 15431,
 12108,
 6240,
 3922,
 8750,
 9855,
 16492,
 11214,
 8600,
 6000,
 5684,
 70761,
 9303,
 9000,
 9297,
 9600,
 4571,
 53227,
 5100,
 7015,
 8004,
 7200,
 8281,
 11988,
 8430,
 3072,
 10628,
 9480,
 11428,
 9291,
 6820,
 11952,
 3675,
 14977,
 5330,
 8480,
 13125,
 13693,
 10637,
 5925,
 16033,
 11846,
 2500,
 4500,
 7758,
 9600,
 10289,
 12243,
 10800,
 1526,
 2665,
 9490,
 15578,
 7931,
 5784,
 7879,
 12692,
 9120,
 7800,
 7535,
 1890,
 9803,
 9170,
 15602,
 2308,
 7596,
 9554,
 7862,
 9600,
 9600,
 14559,
 6792,
 9100,
 9187,
 10594,
 12220,
 10448,
 10208,
 9531,
 10918,
 10800,
 11988,
 5000,
 40094,
 11787,
 7500,
 13300,
 14948,
 9098,
 32668,
 10200,
 6155,
 7200,
 5000,
 9056,
 7000,
 8924,
 12735,
 11553,
 11423,
 14601,
 11000,
 10140,
 4058,
 17104,
 13837,
 8737,
 7244,
 8235,
 9375,
 4043,
 6000,
 11146,
 8777,
 10625,
 6380,
 14850,
 11040,
 21872,
 3196,
 11341,
 10010,
 13907,
 21780,
 13346,
 6858,
 11198,
 10171,
 12327,
 7032,
 13101,
 7332,
 13159,
 9967,
 10500,
 8480,
 6292,
 11777,
 3604,
 12150,
 14585,
 12704,
 11841,
 13500,
 6120,
 11443,
 10267,
 8740,
 25095,
 9100,
 8320,
 13478,
 6600,
 4435,
 7990,
 11302,
 3600,
 3922,
 12984,
 1950,
 10927,
 9000,
 10041,
 3182,
 12803,
 13600,
 12464,
 7800,
 12168,
 7943,
 11050,
 10395,
 11885,
 8402,
 1491,
 8800,
 7861,
 7227,
 11694,
 12244,
 8248,
 10800,
 7064,
 2117,
 10400,
 10000,
 12342,
 9600,
 11606,
 9020,
 9000,
 4590,
 11900,
 9250,
 6979,
 10896,
 6120,
 6000,
 8777,
 3982,
 12677,
 7050,
 13860,
 10793,
 9187,
 10530,
 7200,
 10452,
 7700,
 1936,
 8125,
 9084,
 8750,
 10320,
 10437,
 1680,
 10007,
 7200,
 17503,
 9937,
 12384,
 46589,
 13560,
 10012,
 20896,
 11194,
 18450,
 8125,
 14175,
 11600,
 8633,
 6629,
 11250,
 14442,
 9200,
 2289,
 9600,
 9022,
 11844,
 9945,
 8012,
 4500,
 2887,
 11248,
 16770,
 5062,
 10207,
 5105,
 8089,
 7577,
 4426,
 21535,
 26178,
 5400,
 6120,
 13811,
 6000,
 6420,
 8450,
 4282,
 14331,
 9600,
 12438,
 7630,
 8400,
 5600,
 115149,
 6240,
 9018,
 7162,
 4130,
 8712,
 4671,
 9873,
 13517,
 10140,
 10800,
 10000,
 10542,
 9920,
 6563,
 4426,
 8120,
 8172,
 13286,
 6960,
 21695,
 7314,
 11475,
 6240,
 5389,
 9590,
 11404,
 10000,
 8978,
 10800,
 8544,
 10463,
 10800,
 9313,
 9600,
 6768,
 8450,
 12886,
 5395,
 8963,
 8795,
 11700,
 10593,
 8405,
 8800,
 7750,
 9236,
 10240,
 7930,
 3230,
 10769,
 11616,
 2280,
 12257,
 9100,
 6911,
 8640,
 9430,
 9549,
 14587,
 10421,
 12508,
 9100,
 53504,
 7252,
 8877,
 7819,
 10150,
 14226,
 4500,
 11210,
 13350,
 8400,
 10530,
 7875,
 7153,
 16285,
 9101,
 6300,
 9790,
 10800,
 10142,
 6000,
 12205,
 3182,
 11333,
 9920,
 9158,
 10832,
 8400,
 8197,
 7677,
 13518,
 7200,
 12798,
 4800,
 8199,
 13891,
 9000,
 12274,
 9750,
 21384,
 13400,
 8100,
 10140,
 4438,
 8712,
 9750,
 8248,
 12137,
 11425,
 13265,
 8816,
 6371,
 7226,
 6000,
 12394,
 9900,
 11216,
 14803,
 6130,
 8529,
 28698,
 2544,
 11900,
 3180,
 9548,
 10004,
 7875,
 9600,
 8100,
 1680,
 9525,
 11767,
 12155,
 10440,
 9020,
 8000,
 12665,
 16647,
 9317,
 15523,
 45600,
 9600,
 4435,
 3196,
 7128,
 12095,
 17920,
 6897,
 10970,
 8125,
 10400,
 11029,
 7642,
 11625,
 9672,
 7931,
 8640,
 8750,
 10656,
 6970,
 14762,
 9938,
 6600,
 8750,
 8892,
 12144,
 5720,
 9000,
 25286,
 8834,
 11782,
 7000,
 7024,
 13758,
 9636,
 6204,
 7150,
 5119,
 8393,
 16466,
 15865,
 12160,
 8064,
 11184,
 8414,
 13284,
 7018,
 7056,
 8765,
 7018,
 12919,
 6993,
 7340,
 8712,
 7875,
 14859,
 6173,
 9920,
 13501,
 11500,
 8885,
 12589,
 11600,
 9286,
 6120,
 6270,
 3000,
 2001,
 9000,
 17140,
 13125,
 11029,
 8462,
 8777,
 10237,
 8012,
 10240,
 15611,
 11999,
 9900,
 11838,
 13006,
 8925,
 9100,
 11670,
 8487,
 27650,
 5825,
 10083,
 9675,
 8760,
 24090,
 12640,
 8755,
 7711,
 25000,
 14375,
 8820,
 8163,
 14536,
 14006,
 9360,
 7200,
 7800,
 7200,
 11075,
 9400,
 7136,
 1300,
 7420,
 8450,
 2572,
 7207,
 12227,
 2308,
 11923,
 11316,
 10237,
 9600,
 7390,
 5925,
 10382,
 10800,
 2268,
 7892,
 11639,
 11414,
 2651,
 5900,
 4274,
 9450,
 8816,
 12122,
 12203,
 3182,
 11250,
 10125,
 10880,
 5310,
 10159,
 12046,
 8125,
 9452,
 17671,
 9760,
 8846,
 12456,
 4712,
 10659,
 11717,
 9786,
 6762,
 ...]

In [35]:
 df["SalePrice"] > 175000

0        True
1        True
2        True
3       False
4        True
        ...
1455    False
1456     True
1457     True
1458    False
1459    False
Name: SalePrice, Length: 1460, dtype: bool

In [37]:
df[ df["SalePrice"] > 200000]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1442,1443,60,FV,85.0,11003,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1447,1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500

In [39]:
df["SaleType"] == "WD"

0       True
1       True
2       True
3       True
4       True
        ...
1455    True
1456    True
1457    True
1458    True
1459    True
Name: SaleType, Length: 1460, dtype: bool

In [40]:
sum(df.SaleType == "WD")

1267

In [43]:
df[(df.SaleType == "WD") & (df.SalePrice > 200000)]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
22,23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1426,1427,60,RL,81.0,10944,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2008,WD,Normal,271000
1442,1443,60,FV,85.0,11003,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1447,1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500

In [44]:
cond1 = df.SaleType == "WD"
cond2 = df.SalePrice > 200000
df[cond1 & cond2]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
22,23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1426,1427,60,RL,81.0,10944,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2008,WD,Normal,271000
1442,1443,60,FV,85.0,11003,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1447,1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500

In [45]:
df[~(df.SaleType == "WD") & (df.SalePrice > 200000)]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
20,21,60,RL,101.0,14215,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,New,Partial,325300
58,59,60,RL,66.0,13682,Pave,NaN,IR2,HLS,AllPub,...,0,NaN,NaN,NaN,0,10,2006,New,Partial,438780
112,113,60,RL,77.0,9965,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2007,New,Partial,383970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1375,1376,20,RL,89.0,10991,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,12,2007,New,Partial,239000
1394,1395,120,RL,53.0,4045,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2006,New,Partial,246578
1413,1414,20,RL,88.0,10994,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,COD,Abnorml,257000
1437,1438,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,New,Partial,394617
1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090

In [46]:
df[df.SalePrice.isin([200000, 230000])]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
22,23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
138,139,60,RL,73.0,9066,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,12,2008,WD,Normal,230000
183,184,50,RM,63.0,11426,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,200000
221,222,60,RL,NaN,8068,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2009,ConLI,Normal,200000
255,256,60,RL,66.0,8738,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Normal,230000
635,636,190,RH,60.0,10896,Pave,Pave,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,3,2007,WD,Abnorml,200000
800,801,60,RL,79.0,12798,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,Shed,400,5,2008,WD,Normal,200000
1033,1034,20,RL,NaN,8125,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Normal,230000
1152,1153,20,RL,90.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,230000
1157,1158,120,RL,34.0,5001,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,230000
1207,1208,20,RL,70.0,9135,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,200000
1244,1245,70,RL,NaN,11435,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,230000
1338,1339,60,RL,95.0,13450,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,200000
1350,1351,90,RL,91.0,11643,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2009,WD,Normal,200000
1410,1411,60,RL,79.0,12420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,230000

In [48]:
df.loc[:, ["MSSubClass", "MSZoning"]]

      MSSubClass MSZoning
0             60       RL
1             20       RL
2             60       RL
3             70       RL
4             60       RL
...          ...      ...
1455          60       RL
1456          20       RL
1457          70       RL
1458          20       RL
1459          20       RL

[1460 rows x 2 columns]

In [49]:
df.loc[3:6, ["MSSubClass", "MSZoning"]]

   MSSubClass MSZoning
3          70       RL
4          60       RL
5          50       RL
6          20       RL

In [50]:
df.loc[1, ["MSSubClass", "MSZoning"]]

MSSubClass    20
MSZoning      RL
Name: 1, dtype: object

In [51]:
df.iloc[0:2, :2]

   Id  MSSubClass
0   1          60
1   2          20

In [52]:
df.iloc[:6, [2, 3, 4, 5]]

  MSZoning  LotFrontage  LotArea Street
0       RL         65.0     8450   Pave
1       RL         80.0     9600   Pave
2       RL         68.0    11250   Pave
3       RL         60.0     9550   Pave
4       RL         84.0    14260   Pave
5       RL         85.0    14115   Pave